### ISSUE TITLE
Question: How to add to UIBarButtonItem?

### ISSUE THREAD

**Issue by mikemee** [gemr/Sheriff#10]
Apologies in advance for what is possibly a newbie question...

I have a bar button item from a storyboard that I've confirmed I'm accessing correctly from the view controller via `self.toolbarItems[2]`.

How can I add a button to this?  I've tried the following with no success:

    GIBadgeView *badge = [GIBadgeView new];
    badge.badgeValue = 5;
    [self.toolbarItems[2].customView addSubview:badge];

Thanks in advance...  I'll happily update the readme with an example once it's working. Judging by StackOverflow, there are quite a few people trying to do similar things, and after trying many libraries, this seemed the cleanest and simplest starting point.

**Comment by mamaral** [comment]
UIBarButtonItem is a subclass of `NSObject`, and not `UIView`, so you can't add subviews to them. Seems to me you'd have to implement your own button or view used in place of the `UIBarButtonItem`, to which you could add the badge to.

**Comment by mikemee** [comment]
Thanks. Yes, I'd caught the UIView part but was hoping the `customView` might be a workaround.

Thanks for the quick response. I'll go and scratch my head a bit. And thanks again for the great contribution of this library!

**Comment by mamaral** [comment]
@mikemee No problem, thank you!
